config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists
  # Defines the root path route ("/")
  # root "articles#index"

  # get 'lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new'
  # get 'lists/:id', to: 'lists#show'
  # get 'lists/:id/edit', to: 'lists#edit'
  # patch 'lists/:id', to: 'lists#update'
  # delete 'lists/:id', to: 'lists#destroy'

  # get 'lists/:id/bookmarks', to: 'bookmarks#index'
  # get 'lists/:id/bookmarks/new', to: 'bookmarks#new'
  # get 'lists/:id/bookmarks/:id', to: 'bookmarks#show'
  # get 'lists/:id/bookmarks/:id/edit', to: 'bookmarks#edit'
  # patch 'lists/:id/bookmarks/:id', to: 'bookmarks#update'
  # delete 'lists/:id/bookmarks/:id', to: 'bookmarks#destroy'

  # get 'lists/:id/bookmarks/:id/movies', to: 'movies#index'

  resources :lists do
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [ :list_id ]
  validates :movie, :list, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
    @bookmark.save
    redirect_to bookmarks_path(@bookmark)
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to bookmark_path(@bookmark), notice: "Bookmark saved!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_path(@bookmark), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
    #redirect_to nelist_path(@list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: "List saved!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @list = List.find(params[:id])
    @list.update
    redirect_to lists_path(@list)
  end

  def destroy
    @list = list.find(params[:id])
    @list.destroy
    redirect_to lists_path(@list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with model: @bookmark do |f| %>
  <%= f.label :bookmark %>
  <%= f.text_field :bookmark %>
  <%= f.submit %>
<% end %>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= link_to bookmark.comment, list_path(list)%></li>
  <% end %>
</ul>

<h3><%= link_to "Create new bookmark", new_bookmark_path %> </h3>

app/views/bookmarks/new.html.erb
<h1>Create new Bookmark</h1>

<%= render "form", task: @bookmark %>

<%= link_to "Back to my lists", lists_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>Your Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list)%></li>
  <% end %>
</ul>

<h3><%= link_to "Create new list", new_list_path %> </h3>

app/views/lists/new.html.erb
<h1>Create new list</h1>

<%= render "form", task: @list %>

<%= link_to "Back to my lists", lists_path%>